name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercises
      id: exercises
      uses: education/autograding-command-grader@v1
      with:
        test-name: Exercises
        setup-command: ''
        command: mvn clean verify
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        EXERCISES_RESULTS: "${{steps.exercises.outputs.result}}"
      with:
        runners: exercises
